barganhou/barganhou/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('register.urls')),
    url(r'^register/', include('register.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

barganhou/register/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^register/', include('register.urls', namespace="register")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^(?P<local_id>[0-9]+)/$', views.local, name='local'),
    url(r'^cart/', views.cart, name='cart'),
]

barganhou/register/models.py
from django.db import models
from datetime import date

states = (('AC', 'Acre'),
          ('AL', 'Alagoas'),
          ('AP', 'Amapá'),
          ('AM', 'Amazonas'),
          ('BA', 'Bahia'),
          ('CE', 'Ceará'),
          ('DF', 'Distrito Federal'),
          ('ES', 'Espírito Santo'),
          ('GO', 'Goiás'),
          ('MA', 'Maranhão'),
          ('MT', 'Mato Grosso'),
          ('MS', 'Mato Grosso do Sul'),
          ('MG', 'Minas Gerais'),
          ('PA', 'Pará'),
          ('PB', 'Paraíba'),
          ('PR', 'Paraná'),
          ('PE', 'Pernambuco'),
          ('PI', 'Piauí'),
          ('RJ', 'Rio de Janeiro'),
          ('RN', 'Rio Grande do Norte'),
          ('RS', 'Rio Grande do Sul'),
          ('RO', 'Rondônia'),
          ('RR', 'Roraima'),
          ('SC', 'Santa Catarina'),
          ('AP', 'São Paulo'),
          ('SE', 'Sergipe'),
          ('TO', 'Tocantins')
         )

class LocalInfo (models.Model):
    name = models.CharField(max_length=50)
    state = models.CharField(max_length=19, default='AL', choices=states)
    city = models.CharField(max_length=50, default='Maceió')
    cep = models.IntegerField(blank=True, null=True)
    street = models.CharField(max_length=300)
    number = models.IntegerField(blank=True, null=True)
    neighborhood = models.CharField(max_length=200)
    latitude = models.DecimalField(max_digits=10, decimal_places=8, blank=True, null=True)
    longitude = models.DecimalField(max_digits=10, decimal_places=8, blank=True, null=True)

    def dict(self):
        return {'name': self.name, 'state': self.state, 'city': self.city, 
            'cep': str(self.cep), 'street': self.street, 
            'number': str(self.number), 'neighborhood': self.neighborhood,
            'id': self.pk}
    
    def __str__(self):
        return self.name
         

class ProductInfo (models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=11, decimal_places=2)
    amount = models.DecimalField(max_digits=12, decimal_places=3)
    date_log = models.DateField(default=date.today)
    local = models.ForeignKey(LocalInfo)
    pucharse = models.CharField(max_length=3, default='Y',
                                choices=(('Y', 'yes'), ('N', 'no')))

    def dict(self):
        return {'name': self.name, 'price': str(self.price), 
            'amount': self.amount, 'local': str(self.local),
            'local_id': self.local.pk, 'id': self.pk}
    
    def __str__(self):
        return self.name

barganhou/register/views.py
from django.shortcuts import get_object_or_404, render
from django.template import RequestContext, loader
from .models import ProductInfo, LocalInfo

def get_product_context(request):
    products = []
    locals = []
    for product in ProductInfo.objects.all():
        products.append(product.dict())
    for local in LocalInfo.objects.all():
        locals.append(local.dict())
    return RequestContext(request, {
		'products': products,
        'locals': LocalInfo.objects.all(),
    })

def index(request):
    return render(request, 'register/index.html', get_product_context(request))

def cart(request):
    return render(request, 'register/cart.html', get_product_context(request))

def detail(request, product_id):
    return render(request, 'register/detail.html',
        {'product': get_object_or_404(ProductInfo, pk=product_id)})

def local(request, local_id):
    return render(request, 'register/local.html',
        {'local': get_object_or_404(LocalInfo, pk=local_id)})

barganhou/register/templates/register/cart.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>Carrinho de compras</title>
    <!-- Incluindo o AngularJS - Google's CDN -->
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js"></script>
    <script src="{% static 'register/shopping_cart.js' %}"></script>
    <!--<script src="js/angular-locale_pt-br.js"></script>-->
    
    <link rel="stylesheet" type="text/css" href="{% static 'register/style.css' %}" />
</head>

<body ng-app="shopping_cart" ng-controller="ShoppingCartController">
    <h1>Carrinho de compras</h1>
    
    <a href="{% url 'register:index' %}">Pesquisar produtos</a>
    
    <div class="bar">
        <!-- Ligação entre o modelo searchString e o campo de texto -->
        <input type="text" ng-model="searchString" placeholder="Digite seu termo de pesquisa">
    </div>
    <ul>
        <!-- Renderiza um elemento li para cada entrada no array de itens. Note o filtro de busca customizado "searchFor". Ele pega o valor do modelo searchString como um argumento. -->
        <li ng-repeat="i in {{products}} | filter:searchString">
            <a href="" ng-click="addItemCart(i)"><div>
                Nome: [[i.name]]
                <br> Preço: [[i.price | currency:'R$ ']] <br> Local: [[i.local]]
            </div></a>
        </li>
    </ul>

    <div>
        <h3>Itens selecionados</h3>
        <ul>
            <li ng-repeat="i in cart">
                <a href="" ng-click="removeItemCart(i)"><div>
                    Nome: [[i.name]]
                    <br> Preço: [[i.price | currency:'R$ ']] <br> Local: [[i.local]]
                </div></a>
            </li>
        </ul>
    </div>
</body>
</html>

barganhou/register/templates/register/detail.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'register/style.css' %}" />

<body>
<h2>Produto: {{ product.name }}</h2>
<ul>
    <li>Preço: R$ {{ product.price }}</li>
    <li>Local: {{ product.local }}</li>
</ul>
<a href="/register/">Voltar</a>
</body>

barganhou/register/templates/register/index.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>Informações de produtos registrados</title>
    <!-- Incluindo o AngularJS - Google's CDN -->
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js"></script>
    <script src="{% static 'register/angular_app_define.js' %}"></script>
    <!--<script src="js/angular-locale_pt-br.js"></script>-->
    
    <link rel="stylesheet" type="text/css" href="{% static 'register/style.css' %}" />
</head>

<body ng-app="register" ng-controller="IndexController">
    <h1>Informações de Produtos</h1>
    
    <div class="optview">
        <a href="{% url 'register:cart' %}">Criar carrinho</a>
        
        <div class="bar">
            <!-- Ligação entre o modelo searchString e o campo de texto -->
            <input type="text" ng-model="searchString" placeholder="Digite seu termo de pesquisa">
        </div>
        
        <div>
            <select ng-model="local.selected">
                <option value="0" selected>--Todos--</option>
                {% for opt in locals %}
                <option value="{{opt.id}}">{{opt.name}}</option>
                {% endfor %}
            </select>
        </div>
    </div>

    <div class="results">
        <!--ul>
            <li ng-repeat="i in {{products}} | filter:searchString">
                <div border-style="solid">
                    <b class="col_left">Nome:</b> <span class="col_right">[[i.name]]</span> <br>
                    <b class="col_left">Preço:</b> <span class="col_right">[[i.price | currency:'R$ ']]</span> <br>
                    <a href="/register/[[i.local_id]]/"><b class="col_left">Local:</b> <span class="col_right">[[i.local]]</span></a>
                </div>
            </li>
        </ul-->
        
        <table>
        <tr>
            <th>Nome</th>
            <th>Preço</th>
            <th>Local</th>
        </tr>
        <tr ng-repeat="i in {{products}} | filter:searchString">
            <td>[[i.name]]</td>
            <td>[[i.price | currency:'R$ ']]</td>
            <td><a href="/register/[[i.local_id]]/">[[i.local]]</a></td>
        </tr>
        </table>
    </div>
</body>
</html>

barganhou/register/templates/register/local.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>Informações de produtos registrados</title>
    <!-- Incluindo o AngularJS - Google's CDN -->
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js"></script>
    <script src="{% static 'register/angular_app_define.js' %}"></script>
    <!--<script src="js/angular-locale_pt-br.js"></script>-->
    
    <link rel="stylesheet" type="text/css" href="{% static 'register/style.css' %}" />
</head>

<body ng-app="register">
    <h1>Informações sobre {{local.name}}</h1>
    
    <ul>
        <li><b>Endereço:</b> {{local.street}}, 
            {% if local.number %} {{local.number}}, {% endif %}
            {{local.neighborhood}}, {{local.city}} - {{local.state}}
        </li>
        <li><b>CEP:</b> {{local.cep}}</li>
        <li><b>Coordenadas:</b> {{local.latitude}}, {{local.longitude}}</li>
    </ul>
    <a href="/register/">Voltar</a>
</body>
</html>